# Generated by Django 5.1.1 on 2024-10-06 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='duration',
            field=models.FloatField(default=None, null=True),
        ),
    ]
