# Generated by Django 5.1.1 on 2024-10-06 22:41

import videos.name
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_alter_video_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='url',
            field=models.FileField(unique=True, upload_to=videos.name.PathAndName('videos/')),
        ),
    ]
