# Generated by Django 5.1.1 on 2024-10-08 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_video_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='parent',
        ),
    ]
