# Generated by Django 5.1.1 on 2024-10-06 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_rename_user_video_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='user_id',
            new_name='user',
        ),
    ]
