# Generated by Django 5.1.1 on 2024-10-06 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0006_alter_video_file_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='file_hash',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
