# Generated by Django 5.1.1 on 2024-10-06 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0007_alter_video_file_hash'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='url',
            new_name='video_file',
        ),
    ]
