# Generated by Django 5.1.1 on 2024-10-06 23:28

import videos.name
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0008_rename_url_video_video_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='file_hash',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(upload_to=videos.name.PathAndName('videos/')),
        ),
    ]
