# Generated by Django 5.1.1 on 2024-10-07 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_rename_post_comment_video_id'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='comment',
            table='comment',
        ),
    ]
