# Generated by Django 5.1.1 on 2024-10-05 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videosManager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='url',
            field=models.CharField(default='', max_length=255),
        ),
    ]
