# Generated by Django 5.1.1 on 2024-10-05 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videosManager', '0002_video_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='categories',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
