# Generated by Django 5.1.1 on 2024-10-05 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videosManager', '0003_remove_video_categories_delete_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='url',
            field=models.FileField(upload_to='videos/'),
        ),
    ]
