# Generated by Django 5.1.1 on 2024-10-09 21:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='codesnippet',
            name='like_count',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='codesnippet',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='liked_snippets', to=settings.AUTH_USER_MODEL),
        ),
    ]
