# Generated by Django 5.1.1 on 2024-10-09 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_codesnippet_like_count_codesnippet_liked_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='codesnippet',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='a_media/codesnippets/'),
        ),
    ]
